# This workflow will build a Kotlin project with Gradle

name: Build Kotlin Project

on:
  pull_request:
    branches:
      - '**' # matches every branch
  push:
    branches:
      - '**' # matches every branch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.1
        with:
          gradle-version: 7.4.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run
        run: ./gradlew build